-- Utilize o banco de dados Loja e insira infomações de clientes com nome, email e cidade. 

CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE CLIENTE (
ID INT auto_increment PRIMARY KEY,
NOME VARCHAR(50),
EMAIL VARCHAR(50),
CIDADE VARCHAR(20)
);

INSERT INTO CLIENTE (NOME, EMAIL, CIDADE) VALUES
('LUAN CARLOS', 'LUANCARLOS@GMAIL.COM', 'SALVADOR'),
('VANESSA SANTOS', 'VANESSASANTOSS@GMAIL.COM', 'CAMAÇARI'),
('JOÃO SILVA', 'JOAO@GMAIL.COM', 'SIMÕES FILHO'),
('VICTOR LIZ', 'VICTORLIZ@GMAIL.COM', 'VERA CRUZ');

SELECT ID, NOME, EMAIL, CIDADE
FROM CLIENTE;
